Cloudflare KV Edge Lookup for Subdomains
meetnearme/api pull request #115
Opened 2024-08-28 16:30 UTC by brianfeister

This PR is a partial / first pass, introducing 

1. An API endpoint for adding a new item to KV store from within your `/admin/profile` section
2. An appended header that is (for now) the user ID of the user who added that header

#### Problems

⚠️ Users can currently "grab" multiple subdomains and we need logic to prevent abuse / greedy subdomain grabbing 

![image](https://github.com/user-attachments/assets/e71b7463-d6af-4e18-9ee3-36d6bd0f7222)

2024-08-30 18:01 UTC, Brandon-G-Tripp commented on .editorconfig
Is this meant to be checked in for maintaining consistent formatting across the team?

2024-08-30 18:02 UTC, Brandon-G-Tripp commented on .env.example
@brianfeister can we get these new env variables documented in the README.

2024-08-30 18:06 UTC, Brandon-G-Tripp commented on .github/actions/set_aws_creds_env_vars/action.yml
I see that the cloudflare values are used as inputs but I do not see them used in the action. Are they just used internally for the worker?

2024-08-30 18:48 UTC, Brandon-G-Tripp commented on worker/index.js
> +    let newRequest = new Request(req);
I am getting a linter warning to have this be const since it is never reassigned.

2024-08-30 18:50 UTC, Brandon-G-Tripp requested changes
I just have the couple of small comments to change and add documentation of new env variables and then a bit more test coverage. Should we force past the coverage for now?

2024-09-01 04:03 UTC, brianfeister commented on worker/index.js
> +    let newRequest = new Request(req);
Will fix

2024-09-01 04:04 UTC, brianfeister commented on .github/actions/set_aws_creds_env_vars/action.yml
They're used over here in the Cloudflare / Wrangler worker deploy

https://github.com/meetnearme/api/pull/115/files/4324f6f90f2bb3d71d3f662812fd4de9c9dccc1e#diff-b2da012ee27f5cf144e34765250f8d30034a50f4073447502c81cddb8c60178fR67-R71

2024-09-01 04:06 UTC, brianfeister commented on .github/actions/set_aws_creds_env_vars/action.yml
Also used here in the route handler

https://github.com/meetnearme/api/pull/115/files/4324f6f90f2bb3d71d3f662812fd4de9c9dccc1e#diff-019ebe66f31368757e15573c1255b7a2e0403b52bf1e6170e6833ee64f491e10R56-R57

2024-09-01 04:06 UTC, brianfeister commented on .editorconfig
Yeah, this is to help me (and others), seems 2 tab indent is the go default via `gofmt` which we need to introduce for CI linting checks

2024-09-01 04:07 UTC, brianfeister commented
I'm hoping to get the coverage up and stick to our promise to ourselves. Admittedly, it's a bit tough with our tight timeline

2024-09-01 04:08 UTC, brianfeister commented on .env.example
Will do

2024-09-02 14:05 UTC, brianfeister commented
Coverage resolved @Brandon-G-Tripp mocking that new controller I just added for the KV work. LFG!!! 🔥  Let's merge this before things get crazier. 

Cursor.ai did insane heavy lifting getting me through writing that test... was quite a big chunk of code. 💪

2024-09-02 14:17 UTC, brianfeister commented on .env.example
Actually, I'm not expecting us to document env vars. `.env.example` is the documentation and **must** be looked at. I'll add a note to look there. I've updated this

2024-09-02 14:46 UTC, Brandon-G-Tripp approved these changes
Love to see this!

2024-09-02 14:46 UTC, Brandon-G-Tripp commented on .env.example
Beautiful! Thank you. This will save us when we forget all of our variables.

2024-09-02 14:46 UTC, merged