[WIP] Setup routing and middleware
meetnearme/api pull request #31
Opened 2024-03-22 01:53 UTC by j4inam

This PR implements a web-framework to handle routing and middleware.

2024-03-23 23:50 UTC, brianfeister commented on internal/transport/lambda/router.go
> +package transport
@j4inam why is the `internal/transport/lambda` directory outside of the `functions/lambda` directory? I'm assuming both directories should contain our Go code, why not have them share a directory?

2024-03-23 23:53 UTC, brianfeister commented on internal/transport/lambda/error_handlers.go
> +func SendServerError(err error) (Response, error) {
In a follow-up PR, we probably want this function to have two "modes" :

1) Send an http error with a non-200 status. This would be for JSON data APIs that are leveraged by HTMX and expected to respond with HTML page partials
2) Send a HTML error page for showing an error page to the user, if for example DynamboDB fails to connect and we error out in that way

2024-03-23 23:53 UTC, brianfeister commented on internal/transport/lambda/error_handlers.go
> +func SendServerError(err error) (Response, error) {
If that sounds agreeable, let's open a Github issue to track that

2024-03-23 23:59 UTC, brianfeister commented on functions/lambda/handlers/page-handlers.go
> +	layoutTemplate := pages.App("Meet Near Me - Home", demoCard)
For SEO, it might be good to have all pages include `Meet Near Me` with only the `Home` as an argument passed in by each helper function. This should ultimately concatenate to `Meet Near Me - Home` with only `Home` being the string passed here

2024-03-24 00:01 UTC, brianfeister commented on functions/lambda/main.go
> -    Country string  `json:"country" validate:"required"`
This code was being used by our `/ POST` endpoint which we should maintain for functionality. It's fine to re-structure, but I just want to confirm that we're not **removing** this `/ POST` endpoint, because we should be including it

2024-03-24 00:02 UTC, brianfeister commented on functions/lambda/main.go
> -}
Thought on how we want to handle a single struct that represents the overall page structure of the app. We should have one. This bit is ok to delete here, but we will want nav to be factored into our express-like framework, even if it's not derived from the declarative route style. But maybe it could be?

2024-03-24 00:03 UTC, brianfeister commented on functions/lambda/main.go
> -}
This functionality needs to migrate to the new framework you're working on, not be deleted

2024-03-24 00:03 UTC, brianfeister commented on functions/lambda/main.go
> -func processPost(ctx context.Context, req events.APIGatewayV2HTTPRequest) (events.APIGatewayV2HTTPResponse, error) {
Mentioned above, this is our `/ POST` API call which is our only way to propagate the DB and should not be removed in the process of your migration, but rather included as a new API route + handler

2024-03-24 00:04 UTC, brianfeister commented on functions/lambda/templates/components/demo_card.templ
> +			<p>If a dog chews shoes whose shoes does he choose?</p>
🤣

2024-03-24 00:04 UTC, brianfeister commented on functions/lambda/templates/components/demo_card.templ
> +templ DemoCard() {
Good for WIP demo code, but let's drop this one as we're not using the "card" component just yet in the final design

2024-03-24 00:05 UTC, brianfeister commented on functions/lambda/templates/components/navbar.templ
> +	<div class="navbar bg-primary shadow-xl rounded-box">
Let's preserve the styles from the navbar in `main` currently

2024-03-24 00:07 UTC, brianfeister commented on functions/lambda/templates/pages/app.templ
> +package pages
We've got `/templates/pages/*` and `template.views/*` but we should migrate the contents of `home.templ` into `app.templ` and probably `app.templ` should be called `templates/pages/home.templ` for clarity

2024-03-24 00:08 UTC, brianfeister commented on tailwind.config.js
> +  ],
I think we want a singular top-level directly like `functions/lambda/templates` so that we're not confused about where the views live. Don't want them spread out in multiple places

2024-03-24 02:45 UTC, brianfeister commented on stacks/StaticSiteStack.ts
> +import { Api, StackContext, StaticSite, use } from 'sst/constructs';
Are we using `StackContext`? Looks like maybe not

2024-03-28 19:15 UTC, j4inam commented on internal/transport/lambda/router.go
> +package transport
Moved transport layer within `functions/lambda`

2024-03-28 22:43 UTC, j4inam commented on internal/transport/lambda/error_handlers.go
> +func SendServerError(err error) (Response, error) {
Created issue #33

2024-03-28 22:44 UTC, j4inam commented on functions/lambda/handlers/page-handlers.go
> +	layoutTemplate := pages.App("Meet Near Me - Home", demoCard)
Added `Meet Near Me` as hardcoded text in app layout

2024-04-01 05:37 UTC, j4inam commented on functions/lambda/main.go
> -    Country string  `json:"country" validate:"required"`
I moved `POST /` to `POST /events` for consistency using the new router.
We can still add events using that endpoint. The handler code is identical to the original setup.

2024-04-01 05:40 UTC, j4inam commented on functions/lambda/main.go
> -}
I migrated that bit to the new handler and created a new route `GET /` which renders the homepage with events list.
This code lives in the services now: https://github.com/meetnearme/api/pull/31/files#diff-5ace55baead0c68bae661e54e511459734fff6353b55fdb96728575772d1bcc1R35

2024-04-01 05:41 UTC, j4inam commented on functions/lambda/main.go
> -}
We can have declarative routing.
Need to iterate over a list of routes to build the router and then pass the same array to NavBar

2024-04-01 05:42 UTC, j4inam commented on functions/lambda/templates/components/demo_card.templ
> +			<p>If a dog chews shoes whose shoes does he choose?</p>
lol this is an actual card example on DaisyUI docs 😂

2024-04-01 05:46 UTC, j4inam commented on stacks/StaticSiteStack.ts
> +import { Api, StackContext, StaticSite, use } from 'sst/constructs';
Removed unused imports

2024-04-01 06:04 UTC, j4inam commented on scripts/sam_cli_entrypoint.sh
> -GOOS=linux go build -o main
This command explicitly tries to build go code instead of letting sst handle it. 
This bit seems to be pointing to incorrect dir as base resulting in go.mod deleting most required dependency as it assumes they're all unused which is incorrect.
Dropping this command fixes running `npm run dev` with sst and dynamodb and not breaking go build

2024-04-01 17:17 UTC, Brandon-G-Tripp approved these changes

2024-04-01 17:17 UTC, Brandon-G-Tripp commented on scripts/sam_cli_entrypoint.sh
> -GOOS=linux go build -o main
Perfect. We probably can eliminate most of that file and comment out or remove the service in the docker compose file.

2024-04-02 02:53 UTC, brianfeister commented on functions/lambda/handlers/data-handers.go
+1 let's fix the file name spelling error here

2024-04-02 02:54 UTC, brianfeister commented on functions/lambda/handlers/data-handers.go
> +	res, err := services.InsertEvent(ctx, db, createEvent)
Should this be `*db` to pass a pointer instead of copying `db`?

2024-04-02 03:00 UTC, brianfeister commented on functions/lambda/main.go
> +	router.GET("/", handlers.GetHomePage, transport.LogRequest)
This one could be an AWS cost-to-serve risk. Are we logging **ALL** GET requests? I'm pretty sure we could crush ourselves with logs / run a high bill if we log all success states. Let's only log error states, and even then, I think we don't want to log ALL error states, just the ones that are most interesting / useful

2024-04-02 03:03 UTC, brianfeister commented on functions/lambda/transport/router.go
> +}
Cleanup needed here, there should only be a single `Router` and not a `NewRouter` not sure which is the keeper

2024-04-02 03:08 UTC, brianfeister commented on functions/lambda/transport/router.go
> +	pathParamMatcher := regexp.MustCompile(":([a-zA-Z]+)")
is `:` character in regex literal here? I assume this is for `/path/:varname`? If my guess is right, can you please add a dummy route that just shows how this works?

For example, add

```
router.GET("/event/:eventId", handlers.GetSingleEventPage, transport.LogRequest)
```

And then add an empty `templ` template that just shows

```
<div>Event ID: {eventId}</div>
```

We want to have a working example of this if I'm understanding correctly. Ultimately we want a test in code, but for now, let's have an example in code

2024-04-02 03:09 UTC, brianfeister commented on functions/lambda/transport/router.go
> +	}
Similar to https://github.com/meetnearme/api/pull/31/files#r1547081136 above, are we capturing the functional nuance in working project code? If not, let's add some working code that exercises this (and tests very soon!) to validate that it works as expected (and the test to ensure it continues to do so!)

2024-04-02 03:11 UTC, brianfeister commented on functions/lambda/main.go
> -}
Let's not worry about this for now. Let's consider it a follow up. I actually don't think I want to expose all of the routes in the navbar ever anyway. But it could be helpful to have a helper object representation of the site to pass around, even if we don't iterate over the whole thing and stuff it in the navigation. But again, let's hold off on this and count it as a future improvement so that this PR doesn't get mired in "just one more thing-ism"

2024-04-02 03:12 UTC, brianfeister commented on stacks/StaticSiteStack.ts
> +import { StackContext, StaticSite } from 'sst/constructs';
Thanks!

2024-04-02 03:13 UTC, brianfeister requested changes
This looks awesome! Very excited to land this! ❗ 

A few of my comments need discussion or changes, so I'll mark as blocking for now, but I think we're very close 🚀

2024-04-10 04:00 UTC, j4inam commented on functions/lambda/main.go
> -}
Opened a new issue #36 for this

2024-04-10 04:02 UTC, j4inam commented on functions/lambda/handlers/data-handers.go
@Brandon-G-Tripp Correct. Most of the code from the original setup will live in the handlers.

2024-04-10 04:04 UTC, j4inam commented on functions/lambda/handlers/data-handers.go
> +	res, err := services.InsertEvent(ctx, db, createEvent)
`db` is of type `*dynamodb.Client` so `db` is essentially a pointer to the client.

2024-04-10 04:04 UTC, j4inam commented on functions/lambda/main.go
> +	router.GET("/", handlers.GetHomePage, transport.LogRequest)
Oh that was just an example to showcase how middlewares can be used with our home grown routing. I can take that logger out.

2024-04-10 04:08 UTC, j4inam commented on functions/lambda/transport/router.go
> +}
`Router` is the struct which contains the `routes` array which is the keeper or the object that actually holds the routes. Since the name `Router` is now taken, I created a `NewRouter` function that returns a pointer to the `Router` instance. I renamed it to `GetRouter` for better clarity

2024-04-10 05:04 UTC, j4inam commented on functions/lambda/transport/router.go
> +	pathParamMatcher := regexp.MustCompile(":([a-zA-Z]+)")
Added `/events/:eventId` route to load the event details page.
To Test: Click on the details button in the events table on the Home page
![Uploading Screenshot 2024-04-10 at 1.03.56 AM.png…]()

2024-04-10 05:06 UTC, j4inam commented on functions/lambda/transport/router.go
> +	}
Replacing path params with values and storing passed values for params in an object is working. I've added a demo route: `/events/:eventId` to demonstrate the same.

The check for dupes bit needs a unit test to be added. Will add that once we have a unit testing framework setup.

2024-04-10 14:38 UTC, brianfeister requested changes
@j4inam Definitely want to get this merged, but the deployment (we need integration tests I think) is throwing `Internal Server Error`

I checked this by going to your latest deployment here
https://github.com/meetnearme/api/actions/runs/8626305835/job/23644293424#step:5:75

And grabbing that URL and checking:
https://baqfmnplod.execute-api.us-east-1.amazonaws.com/

I'm going to pull your branch and see if I can quickly spot the problem and fix

2024-04-10 15:03 UTC, brianfeister commented
The code here looks fine in my local deployment, I'll delete `feature-frontend-setup` in AWS CloudFormation and trigger a re-deploy from fresh

2024-04-10 16:09 UTC, brianfeister commented on functions/lambda/transport/router.go
> +	}
Sounds good, we'll figure out something re: the dupes logic, we can merge now. 

Created the ticket here:
https://github.com/meetnearme/api/issues/37

2024-04-10 16:09 UTC, brianfeister approved these changes
LGTM 🚀

2024-04-10 16:30 UTC, merged