Integrate clerk auth
meetnearme/api pull request #40
Opened 2024-06-07 20:45 UTC by j4inam

## Description
This PR implements authentication via Clerk using clerk-go-sdk v2.

## Changes
- Implement clerk middleware
- Implement login and signup pages
- Implement error handling response for HTTPErrors and displaying fallback htmx error components.

2024-06-10 17:43 UTC, brianfeister commented on functions/lambda/handlers/data-handlers.go
> +		})
Nice 👍

2024-06-10 17:45 UTC, brianfeister reviewed
@j4inam can you add the open TODO's on this or file them as bugs / tickets? The only one I remember is my comment about the password input field being required for launch, I don't want us to do "magic links" only for sign in.

You had mentioned 3 other things, I believe?

I would like to get this merged so we can all have this in `main` to integrate with our own feature work, and I think I'd like to merge it before those changes are in place, I just want to make sure they are tracked

2024-06-10 17:46 UTC, brianfeister commented on functions/lambda/handlers/page-handlers.go
> +	sessionClaims, ok := clerk.SessionClaimsFromContext(ctx)
Not a blocker, but we should demonstrate other session claims (e.g. "roles") as a follow-up. Not required for this PR though

2024-06-10 17:48 UTC, brianfeister commented on functions/lambda/helpers/constants.go
> +	GOOGLE_AUTH       string = "oauth_google"
I saw Discord as an auth option when we looked at your WIP project via video call... does this need to include something regarding Discord? Also, I'm not sure that we really need Discord auth, seems a little less common, and also, I feel like we might want Outlook (Microsoft) auth, since we are calendar-focused and want to add events to calendars as RSVPs

2024-06-10 17:49 UTC, brianfeister commented on functions/lambda/main.go
> +	router.GET("/sign-up", handlers.GetSignUpPage)
Minor nit, let's do `signup` I like to avoid dashes unless a word REALLY needs to be clarified by a delimiter

2024-06-10 17:51 UTC, brianfeister commented on functions/lambda/transport/auth.go
> +	genericClient := client.NewClient(config)
What is `genericClient`? I feel like we might want a better name for this, as it's not immediately obvious to me what this refers to

2024-06-10 17:52 UTC, brianfeister commented on functions/lambda/transport/error_handlers.go
> +func SendHTTPError(httpError *HTTPError) Response {
Awesome 👏

2024-06-10 17:54 UTC, brianfeister commented on functions/lambda/transport/middleware.go
> +func ParseCookies(ctx context.Context, r Request) (context.Context, Request, *HTTPError) {
Interesting ... there's no cookie parser function baked into Go's core libs?

2024-06-10 23:10 UTC, brianfeister commented on functions/lambda/templates/pages/signup.templ
> +	<script async crossorigin="anonymous" data-clerk-publishable-key="pk_test_YnJhdmUtYmVldGxlLTEyLmNsZXJrLmFjY291bnRzLmRldiQ" src="https://brave-beetle-12.clerk.accounts.dev/npm/@clerk/clerk-js@latest/
Is this a secret? Probably should come from env var, right?

2024-06-10 23:15 UTC, brianfeister commented on functions/lambda/transport/middleware.go
> +			ResponseHeaders: map[string]string{"Location": "https://zi01imi18j.execute-api.us-east-1.amazonaws.com/login?redirect=" + r.RawPath},
This is a blocker ❌ 

Needs to use `os.Getenv('API_APEX_URL')` or something similar

Needs to be emitted to `.env` as part of the SST env vars that get exposed here:

https://github.com/meetnearme/api/blob/feature-clerk-auth/stacks/ApiStack.ts#L22

Notice that we emit it to console here 
https://github.com/meetnearme/api/blob/feature-clerk-auth/stacks/ApiStack.ts#L34

That prints it for us to know when we run `npm run dev` locally`, but we need to add it to the above section for env vars so that it's exposed to the Go runtime and can be dynamically set here

2024-06-10 23:16 UTC, brianfeister commented on functions/lambda/templates/pages/login.templ
> +	<script async crossorigin="anonymous" data-clerk-publishable-key="pk_test_YnJhdmUtYmVldGxlLTEyLmNsZXJrLmFjY291bnRzLmRldiQ" src="https://brave-beetle-12.clerk.accounts.dev/npm/@clerk/clerk-js@latest/
Same question as here:

https://github.com/meetnearme/api/pull/40/files#r1633937284

2024-06-10 23:18 UTC, brianfeister requested changes
This one especially is a blocker:
https://github.com/meetnearme/api/pull/40/files#r1633939331

A few others are "maybe a blocker" and then some of the nits are small enough that we should probably just fix them now.

Let me know your thoughts, really want to get this merged, and please add to the PR description of open / unresolved issues for tracking. We can merge with those feature defects

2024-06-12 22:22 UTC, j4inam commented
> @j4inam can you add the open TODO's on this or file them as bugs / tickets? The only one I remember is my comment about the password input field being required for launch, I don't want us to do "magic links" only for sign in.
> 
> You had mentioned 3 other things, I believe?
> 
> I would like to get this merged so we can all have this in `main` to integrate with our own feature work, and I think I'd like to merge it before those changes are in place, I just want to make sure they are tracked

Opened issues #42 #43 #44

2024-06-12 22:23 UTC, j4inam commented on functions/lambda/helpers/constants.go
> +	GOOGLE_AUTH       string = "oauth_google"
I added it as a login option just to demo clerk we can remove discord and keep only email (link + password) and Google login. I disabled Discord login via dashboard.

2024-06-12 22:25 UTC, j4inam commented on functions/lambda/main.go
> +	router.GET("/sign-up", handlers.GetSignUpPage)
Fixed! Refactored to `/signup`

2024-06-12 22:28 UTC, j4inam commented on functions/lambda/transport/middleware.go
> +func ParseCookies(ctx context.Context, r Request) (context.Context, Request, *HTTPError) {
The built in function is for accessing cookies from Go's net/http request. Doesn't really work for Lambdas.
The object structures are different

2024-06-12 22:36 UTC, j4inam commented on functions/lambda/transport/middleware.go
> +			ResponseHeaders: map[string]string{"Location": "https://zi01imi18j.execute-api.us-east-1.amazonaws.com/login?redirect=" + r.RawPath},
I created an issue #45 to address this

2024-06-12 22:38 UTC, j4inam commented on functions/lambda/transport/auth.go
> +	genericClient := client.NewClient(config)
Generic Client is for accessing global clerk features that don't really fall under a specific category like user or organization or session, etc. I can rename it to `clerkClient` or `globalClient` if that adds clarity

2024-06-12 22:40 UTC, j4inam commented on functions/lambda/templates/pages/login.templ
> +	<script async crossorigin="anonymous" data-clerk-publishable-key="pk_test_YnJhdmUtYmVldGxlLTEyLmNsZXJrLmFjY291bnRzLmRldiQ" src="https://brave-beetle-12.clerk.accounts.dev/npm/@clerk/clerk-js@latest/
This is a publishable secret specifically for being used on the front end and it doesn't matter if the value is exposed.
I can move it to env var for code quality purposes but other than that having the exposed is fine.

There's also a server side secret which should not be exposed.

See: https://clerk.com/docs/deployments/clerk-environment-variables#clerk-publishable-and-secret-keys

2024-06-13 02:23 UTC, brianfeister commented on functions/lambda/transport/middleware.go
> +			ResponseHeaders: map[string]string{"Location": "https://zi01imi18j.execute-api.us-east-1.amazonaws.com/login?redirect=" + r.RawPath},
@j4inam this will break me and @Brandon-G-Tripp if the PR merges with this AWS URL. The URL is specific to your deployment on AWS so we can't use this. I've pushed the commit below to demonstrate what I had in mind for resolving this. This should give us a way to override the URL in a way that's specific to each developer's environment

https://github.com/meetnearme/api/pull/40/commits/3aea3199a6e795794507ea0cfcdb8b030dc20807

Let me know if this change works on your side.

On my end, I can't test the PR because I think I have to delete the whole AWS resource array because I guess the Dynamo table change Brandon introduced isn't included here? Not sure 🤔 did you merge upstream `main` into this?

2024-06-13 02:24 UTC, brianfeister commented
@j4inam looks like you need to merge `main` back. Then hopefully I can get a clean deploy with the Dynamo schema change from @Brandon-G-Tripp included on your branch here

2024-06-13 02:29 UTC, brianfeister commented
@j4inam Ideally we name the branch `feature/<my-feature-name>` which triggers the feature branch deployment which would be helpful for testing here. This branch is `feature-clerk-auth` and the lack of `/` after feature fails the regex test for triggering the deploy 

https://github.com/meetnearme/api/blob/main/.github/workflows/deploy-feature.yml#L5

2024-06-20 23:32 UTC, j4inam commented on functions/lambda/transport/middleware.go
> +	domainName := r.RequestContext.DomainName
Fixes #45 . Writes domain name to `context.Context` instead of .env

2024-06-24 04:19 UTC, brianfeister requested changes
@j4inam I really want to get this merged. Here are the issues I'm seeing testing this on my side

1.  The first thing that happened for me running this locally (I was able to now, yay 🎉 ) was going to `/account` throws an error
<img width="925" alt="image" src="https://github.com/meetnearme/api/assets/806536/9095c64d-0248-4059-a506-e7ebc68402b3">
2. When I click "Sign In" I can't get back to the login form to sign in (I see the open bug for 30 second sessions, but how can I log in at all? Do we need some javascript that will clear cookies when clicking "sign in" in order for the backend middleware to not pick that up and try to throw it through auth refresh flow? Screenshot of the issue:
![Screen_Recording_2024-06-23_at_10 17 27 PM] (https://github.com/meetnearme/api/assets/806536/5328380c-a64a-4cf9-9207-8c3e577d8c84)

2024-06-27 13:18 UTC, brianfeister commented on functions/lambda/handlers/data-handlers.go
> +func CreateEvent(ctx context.Context, r transport.Request, db *dynamodb.Client, clerkAuth *transport.ClerkAuth) transport.Response {
@j4inam I think we want this available via middleware so that we're not constantly changing the function signature to something non-standard. That way, only the routes that need a given parameter need to have their code changed. Especially in a situation like this where `clerkAuth` can be a pointer so we're not doing the JavaScript mistake of passing everything by value

2024-07-25 12:50 UTC, brianfeister commented
Unless something changes, we are going with Zitadel auth instead of Clerk:
https://github.com/meetnearme/api/pull/50

2024-07-25 12:50 UTC, closed without merging