Cleanup Seshu form UI 🍴
meetnearme/api pull request #56
Opened 2024-07-13 21:12 UTC by brianfeister

This PR is purely UX-based, improving error messaging and handling as well as state management for the `/admin/add-event-source` route.

2024-07-13 21:15 UTC, brianfeister commented on functions/gateway/handlers/page_handlers.go
> +func GetAddEventSourcePage(w http.ResponseWriter, r *http.Request) http.HandlerFunc {
`Admin` was a placeholder, updating the function naming

2024-07-13 21:16 UTC, brianfeister commented on functions/gateway/handlers/partial_handlers.go
> -	geoLookupPartial := partials.GeoLookup(lat, lon, address, false)
The boolean logic for switching in the template isn't needed, simplifying since we always respond with `Location Confirmed`

2024-07-13 21:16 UTC, brianfeister commented on functions/gateway/handlers/partial_handlers.go
> +	var inputPayload SeshuSessionSubmitPayload
This was a copy / paste error and should have never been `SeshuSessionEventsPayload`

2024-07-13 21:17 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +			<form class="group" novalidate hx-post={ templ.EscapeString(os.Getenv("SESHU_FN_URL")) } hx-ext="json-enc" hx-target="#event-candidates-inner" hx-disabled-elt="input[name='url'], button[type='subm
Doing more than one thing in the `handle*` functions, so moved them to the `<script>` below

2024-07-13 21:17 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +						<input x-model="hasFallbackLocation" id="event-candidates-location-toggle" type="checkbox" class="toggle toggle-success mr-4" />
Need to track this value at the Alpine form state level

2024-07-13 21:18 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +								@htmx:after-request="handleLocationValidation(event)"
This is the main change, since we need to change formState (`this.locationValidated`) only if successful

2024-07-13 21:21 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +								<button type="submit" :disabled="!formData.address?.length || !formData.url?.length" class="btn btn-primary mt-3">
It is now (finally!) not possible to submit the form if the various permutations of valid state are not satisfied. They are:

1. MUST have a URL
2. MUST confirm events are really events (after toggling the green / red event cards)
3. MUST enter a string of some kind to get a map via Google map query
4. MUST confirm Location, BUT ONLY IF the toggle is checked (starts off checked by default because we want to encourage fallback location to be able to error on the side of pulling in more events)

If all of the above are satisfied, the submit button should be enabled, if not, should be disabled

2024-07-13 21:22 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +					@htmx:after-request="handleFinalSubmission(event)"
Sets the `formStep` to 3, highlighting the top left final step

2024-07-13 21:25 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +					/>
This is an HTMX quirk, since the Go API Gateway calls for these HTMX endpoints require `url` as part of the payload, the default behavior pre-React days was to include that as part of a named input field in the form (`<input name="url" />` in this case.

We leverage Alpine's `x-model` to always keep the value in sync, but we make the input field hidden in all cases aside from the first input field where users enter the value

2024-07-13 21:25 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +						:disabled="!hasEvents || !eventsValidated || (hasFallbackLocation && !locationValidated) || formStep < 2"
The conditions that satisfy the enabling of the submit button

2024-07-13 23:13 UTC, Brandon-G-Tripp reviewed
@brianfeister Hey since this PR is related to the Seshu UI and following the Zitadel reference I would love to see the flow for adding the callback URL and related values to the .env and also the documentation in the README for setting that up in the Zitadel console.

2024-07-13 23:31 UTC, Brandon-G-Tripp commented on functions/gateway/templates/pages/add_event_source.templ
> +								<button type="submit" :disabled="!formData.address?.length || !formData.url?.length" class="btn btn-primary mt-3">
Ok I opened an issue for number 2. Small bug in my opinion that may want to be incorporated into this PR. The confirm event data button allows submitting even if all events are shown to be invalid by the user. May need different handling or just a UI change for the message. 

See - #58

2024-07-13 23:33 UTC, Brandon-G-Tripp commented on functions/gateway/templates/pages/add_event_source.templ
> +								<button type="submit" :disabled="!formData.address?.length || !formData.url?.length" class="btn btn-primary mt-3">
<img width="1426" alt="Screen Shot 2024-07-13 at 5 32 17 PM" src="https://github.com/user-attachments/assets/d6baa00d-317f-49d4-83cb-18e29607baaa">

The UI allowed me to click Submit event source even without a string of any kind in the event address field.

2024-07-13 23:37 UTC, Brandon-G-Tripp requested changes
Hey everything looks good overall. I just want to confirm the UX flow that did not seem to function correctly in light of the Submit Event Source button. The main change being able to submit the event source without the string for the Google Maps rendering. 

The second item was the ability to confirm the event data even if all events were select as not events and then the need to have a differing message if no events are selected and prevent submission. @brianfeister

2024-07-14 13:21 UTC, brianfeister commented
@Brandon-G-Tripp 

> I just want to confirm the UX flow that did not seem to function correctly in light of the Submit Event Source button. The main change being able to submit the event source without the string for the Google Maps rendering.

I see what you mean, the `Confirm Location` button was enabled with no address provided. That's what you're saying right? I've fixed that here https://github.com/meetnearme/api/pull/56/commits/f11da851df313f05bf5c7e28ab0904aa4998fb5f

The bug you opened for #58 is fixed in this commit:
https://github.com/meetnearme/api/pull/56/commits/3b57a2f3ffb8b46fcea51b29f6be6e0c4da236d3

2024-07-14 13:25 UTC, brianfeister commented
@Brandon-G-Tripp also, great job on the QA aspect of testing this 🏆 

Noticing those UX issues and then requesting changes was the right thing to do!

2024-07-15 12:07 UTC, brianfeister commented on functions/gateway/templates/pages/add_event_source.templ
> +								<button type="submit" :disabled="!formData.address?.length || !formData.url?.length" class="btn btn-primary mt-3">
This should be fixed now 👍

2024-07-15 20:01 UTC, Brandon-G-Tripp approved these changes
Ok I am satisfied with this. I think everything is good to go for this PR. With the follow up PR approved as well.

2024-07-15 20:01 UTC, merged