Dynamodb prod wire up [DO NOT MERGE]
meetnearme/api pull request #8
Opened 2024-02-14 02:38 UTC by brianfeister

**[WIP - this needs cleanup]**

This PR does the following:

* Wire up prod + local dynamodb and make the code interoperable between the two
* Show a basic list of events on the home page, this event list is populated live from dynamoDb (total page response times feel like they're around ~500ms **including the DB read** which is 🔥🔥🔥)

## Video of it in action

![Screen_Recording_2024-02-13_at_7 33 47 PM](https://github.com/meetnearme/api/assets/806536/74c9f09b-8a2d-4def-a3d9-994be0a8d283)

2024-02-14 22:12 UTC, brianfeister commented
I think mainly it's just cleanup, there's a bunch of irrelevant code and
comments. I've been trying to get environment variables figured out but I
should do this in a follow up PR

On Wed, Feb 14, 2024, 1:12 PM Brandon Tripp ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> This looks like some great progress. Awesome that we are getting some
> momentum and looks like the pieces are coming together. @brianfeister
> <https://github.com/brianfeister> what do you need to finish and for the
> merge?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/meetnearme/api/pull/8#pullrequestreview-1881207762>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGE5CGA35WXP3Z2HUJDNWLYTULCHAVCNFSM6AAAAABDHRC5LSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBRGIYDONZWGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-14 22:14 UTC, brianfeister commented
@Brandon-G-Tripp one thing that's new for me is the whole `myFunc( *var )` pass by reference rather than value thing. Can you keep me honest and check if I've missed any opportunities along those lines?

2024-02-16 16:08 UTC, brianfeister commented
@Brandon-G-Tripp I think this is ready to merge now. Let me know if anything in the Go code looks less than idiomatic

2024-02-19 16:05 UTC, Brandon-G-Tripp requested changes
Ok I do not seeing anything that is sticking out or does not seem idiomatic. I think it all looks good besides bumping those github actions before we merge.

2024-02-19 16:05 UTC, Brandon-G-Tripp commented on .github/workflows/deploy-prod.yml
> +        uses: aws-actions/configure-aws-credentials@v2
Same with this aws-actions/ v4 was released a couple of weeks ago. I think we should bump it now before we get to far to see if we have any breaking changes.

2024-02-19 16:05 UTC, Brandon-G-Tripp commented on functions/lambda/dynamodb.go
> +    var SST_Table_tableName_Events = os.Getenv("SST_Table_tableName_Events")
Just a question on this. Where do we load the .env?

2024-02-19 18:14 UTC, brianfeister commented on .github/workflows/deploy-prod.yml
> +        uses: actions/checkout@v3
Good catch, fixing now

2024-02-19 18:15 UTC, brianfeister commented on .github/workflows/deploy-prod.yml
> +        uses: aws-actions/configure-aws-credentials@v2
Good call, pushing a fix to test if anything breaks

2024-02-19 18:20 UTC, brianfeister commented on functions/lambda/dynamodb.go
> +    var SST_Table_tableName_Events = os.Getenv("SST_Table_tableName_Events")
The `.env` is a mistake and I removed it from this PR. The call to it will appear in my next PR that introduces env vars (very important!) 

I don't want this PR to add it now, as it would create confusion when looking at the upcoming PR, there is no clear addition of `.env` to `.gitignore` which would be weird

2024-02-19 18:22 UTC, brianfeister commented
@Brandon-G-Tripp resolved all of your comments and the deployment run passes with the updated versions of the github actions modules

2024-02-19 18:33 UTC, Brandon-G-Tripp commented on functions/lambda/dynamodb.go
> +    var SST_Table_tableName_Events = os.Getenv("SST_Table_tableName_Events")
Perfect makes sense. Just wanted to clarify because the Getenv is a bit tricky. I have been using godotenv package for other projects and seems to be the main package in use in the go ecosystem.

2024-02-19 18:35 UTC, Brandon-G-Tripp approved these changes
It looks good to me to move onto the env vars and next features.

2024-02-19 18:35 UTC, merged