Update go.yml
meetnearme/api pull request #81
Opened 2024-07-26 21:58 UTC by Brandon-G-Tripp

Add run of Go tests to workflow file and coverage report. Uploads coverage report to repository for reference.

Patch to add CI check for test coverage at 50% and all tests passing.

2024-07-27 01:48 UTC, brianfeister requested changes
It looks like there's an error in the grep command and the coverage check you added is failing, but not due to threshold

2024-07-27 01:50 UTC, brianfeister commented
Also, do we want to be piping these to txt files? I'm not sure what the exact limit is, but GitHub allows for artifacts from test runs but storage is not unlimited

2024-07-27 01:57 UTC, brianfeister commented
Sorry, still processing this. Sooooo is exiting `1` expected behavior because that signals that the threshold isn't met? If that's the case I think we want to echo something in the output rather than silently failing without explanation that the coverage threshold is unmet

2024-07-31 23:19 UTC, msnorth approved these changes

2024-07-31 23:19 UTC, msnorth commented on .github/workflows/go.yml
> +            echo "🟠 Coverage is $COVERAGE%. It's passing but is close to the failure cutoff."
I think Java had some sort of utility we used which made sure our coverage never decreased. This is good for now but something to think of

2024-07-31 23:22 UTC, brianfeister approved these changes

2024-08-01 00:09 UTC, brianfeister approved these changes

2024-08-01 00:09 UTC, merged